DROP TABLE IF EXISTS `DebiteurTable`;

CREATE TABLE `DebiteurTable` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `email` varchar(255) default NULL,
  `voornaam` varchar(255) default NULL,
  `tussenvoegsel` TEXT default NULL,
  `achternaam` varchar(255) default NULL,
  `totaal` varchar(100) default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `Debiteur` (`email`,`voornaam`,`tussenvoegsel`,`achternaam`,`totaal`)
VALUES
  ("molestie.pharetra@yahoo.net","Ali","De","Small","€66.84"),
  ("sagittis.placerat@hotmail.ca","Acton","Van","Singleton","€70.32"),
  ("at@aol.ca","Chiquita","Van","Livingston","€11.37"),
  ("hendrerit.neque@google.edu","Ainsley","Van","Carpenter","€66.09"),
  ("non.ante@aol.couk","Aladdin","Van","Park","€52.69"),
  ("cursus.a@aol.com","Driscoll","De","Donaldson","€98.47"),
  ("a.nunc@outlook.net","Adena","Van","Reilly","€34.47"),
  ("adipiscing.non@google.ca","Morgan","Van","Haynes","€84.50"),
  ("dui@outlook.edu","Randall","Van","Kirk","€59.90"),
  ("aliquam.adipiscing@protonmail.org","Nolan","Van","Copeland","€79.66"),
  ("augue.eu@hotmail.com","Vladimir","De","Cannon","€17.82"),
  ("ante.lectus@yahoo.couk","Prescott","De","Henderson","€31.84"),
  ("imperdiet.ornare.in@hotmail.edu","August","De","Walters","€88.92"),
  ("cras.sed@protonmail.edu","Lunea","De","Miller","€26.03"),
  ("duis.mi.enim@icloud.org","Dillon","De","Delgado","€55.36"),
  ("dictum.phasellus@yahoo.ca","Holly","Van","Rojas","€59.85"),
  ("est@aol.net","Amal","Van","Beasley","€52.60"),
  ("ac.ipsum.phasellus@outlook.org","Chelsea","De","Giles","€42.69"),
  ("amet@icloud.ca","Wyoming","Van","Sweet","€92.05"),
  ("quam@aol.net","Ulric","De","Mckay","€82.06"),
  ("adipiscing.lobortis@icloud.com","Berk","De","Meyers","€65.22"),
  ("nunc.quisque@hotmail.couk","Malachi","De","Horne","€93.48"),
  ("magnis.dis@outlook.net","Amery","Van","Ratliff","€24.29"),
  ("nunc.nulla@yahoo.couk","Dalton","De","Simon","€25.76"),
  ("vestibulum.ante.ipsum@icloud.edu","Alika","De","Deleon","€73.43"),
  ("et.euismod@hotmail.couk","Perry","De","Lara","€52.33"),
  ("vestibulum.massa@protonmail.com","Hyatt","De","Conrad","€42.60"),
  ("morbi.neque@icloud.com","Lewis","Van","Brown","€74.02"),
  ("non.lobortis@protonmail.couk","Raja","De","Nguyen","€12.52"),
  ("sed@hotmail.net","Idona","De","Hooper","€48.36"),
  ("in@outlook.couk","Jamalia","De","Ware","€42.46"),
  ("lobortis.mauris@google.couk","Hanna","Van","Duffy","€86.64"),
  ("ante@icloud.com","Arden","Van","Cannon","€49.55"),
  ("lacinia.mattis@protonmail.org","Judith","Van","Mccormick","€78.30"),
  ("risus.nunc.ac@hotmail.org","Desiree","De","Rose","€16.18"),
  ("eget.volutpat@yahoo.com","Sade","Van","Cote","€74.96"),
  ("dapibus.gravida@aol.couk","Dieter","De","Reeves","€61.81"),
  ("erat.vel.pede@hotmail.org","Inez","De","Sloan","€67.26"),
  ("tincidunt@hotmail.edu","Alexandra","De","Duran","€15.86"),
  ("accumsan.laoreet.ipsum@aol.net","Jaden","De","Holt","€27.59");
